type: map
mapping:
    key: 
       type: seq
       required: True
       sequence:
       - type: int
       - type: int
       - type: int
       - type: int
       - type: str
              
    stave:
       type: seq
       required: True
       sequence: 
       - type: int
       - type: int
       - type: int
       - type: int
       - type: str  